### ISSUE TITLE
大佬可以增加上角标与下角标吗?

### ISSUE THREAD

**Issue by lolisix** [rimebrew/rime_latex#1]
虽然unicode中的上下角标很丑,但是特殊情况也可以用到呀!
奈何我十载不会加入,只能求大佬帮忙了.

**Comment by shenlebantongying** [comment]
可以，那两个？有没有现成的对应的 latex 命令？

只要往 dict 文件里面添加就可以

https://github.com/rimebrew/rime_latex/blob/main/latex.dict.yaml

**Comment by lolisix** [comment]
就是所有的₂²这样的上下角标,u码里面所有的数字与英文字母都有上下角标,部分希腊字母有上下角标.我之前研究好久,成功加入里面了.latex命令,就是(o/u)代表over上标/under下标,再加对应的字符,比如2、e、alpha.

**Comment by shenlebantongying** [comment]
那我们这样弄？
```
\o1 -> ¹
\o2 -> ²
```

**Comment by shenlebantongying** [comment]
我把你加入了这个仓库的管理权限了，如果你觉得有合适的可以加进去，可以直接提交到仓库里面。

**Comment by shenlebantongying** [comment]
https://github.com/rimebrew/rime_latex/commit/3329da7998fdd637c4b4718896526403ec9180dc#diff-7d2bcb0a5cd7f90b175b2a24eec1eca9fdff00561b68b64e11c34e540223c402
