### ISSUE TITLE
目前建议的拼音混用似乎会对断字产生严重影响

### ISSUE THREAD

**Issue by Iey4iej3** [rimebrew/rime_latex#22]
例如输入 ceshi，会出现候选词

测试 ~shi

选取改候选词后，输入框变成 测试shi，并且出现对 shi 的候选。这会严重影响输入，似乎得不偿失。

**Comment by lifeformg** [comment]
我也遇到了这个问题，现在已经解决了。目前定位到问题是xxx.custom.yaml里面的：
```
engine/translators:
    - punct_translator
    - table_translator
    - table_translator@latex_input
```
这一段导致的问题。
我将这部分修改为：
```
engine/+:
    translators/+:
      - table_translator@latex_input
```
断字就正常了。
猜测可能是readme里面给的engine/translators不全？导致原本有些重要的engine/translators被覆盖了？
我也不懂……是chatgpt说这段可能有问题让我改的。
@shenlebantongying 考虑要不要改下readme

**Comment by shenlebantongying** [comment]
改了

**Comment by Iey4iej3** [comment]
好像少了一个冒号。我提交了一个 PR，但不清楚怎么和这个工单链接起来，合并后自动关闭这个工单。

**Comment by lifeformg** [comment]
> 好像少了一个冒号。我提交了一个 PR，但不清楚怎么和这个工单链接起来，合并后自动关闭这个工单。

确实，我复制漏了

**Comment by shenlebantongying** [comment]
> 怎么和这个工单链接起来，合并后自动关闭这个工单。

加一行 fix ... 就行，比如

fix #22

https://docs.github.com/zh/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
